
version: '3.8'
services:
  langflow:
    image: ghcr.io/sideral-tech/langflow-docker:latest
    restart: unless-stopped
    ports:
      - 7860:7860
    volumes:
      - /data/langflow/data:/home/langflow/.cache/langflow
      - /data/langflow/logs:/home/langflow/app/logs
    environment:
      - LANGFLOW_AUTO_LOGIN=False
      - LANGFLOW_SUPERUSER=MyAdminUsername
      - LANGFLOW_SUPERUSER_PASSWORD=MySuperSecretPasswordOmg11!
      - LANGFLOW_SECRET_KEY=GenerateOneWithOpensslRandBase64
